[versions]
compose = "1.5.1"
kotlin = "1.9.0"

[libraries]
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jb-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
